# Generated by Django 2.2.4 on 2020-05-08 09:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=30)),
                ('Name', models.CharField(max_length=25)),
                ('Message', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ads1', models.TextField(max_length=500, null=True)),
                ('Ads2', models.TextField(max_length=500, null=True)),
                ('Ads3', models.TextField(max_length=500, null=True)),
                ('Ads4', models.TextField(max_length=500, null=True)),
                ('Ads5', models.TextField(max_length=500, null=True)),
                ('Ads6', models.TextField(max_length=500, null=True)),
                ('Ads7', models.TextField(max_length=500, null=True)),
                ('Ads8', models.TextField(max_length=500, null=True)),
                ('User', models.OneToOneField(on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
